lejard-h/chopper

chopper/lib/src/request.dart
At the moment, if you provide a fully-qualified URL in the `url` parameter for a request, it gets concatenated to the `baseUrl` (which is not correct). No matter what value you set `baseUrl` to, you just can't prevent it from concatening both `baseUrl` and `url`.
This change changes the logic so that if the `url` parameter is a fully formed URL, we can just use it directly instead of trying to combine it with the `baseUrl`.
=> Allow fully-specific URLs to be provided

chopper/lib/src/base.dart
This change resolves an ambiguity between the HTTP and JSON RFCs.
I've added a detailed comment in the code that describes what we're doing and why.
=> Decode json using utf-8

chopper/pubspec.yaml, chopper_generator/pubspec.yaml, example/pubspec.yaml
Removed 2.0.0-dev sdk since dart 2.0.0 is at stable now (so is flutter)
=> Removed 2.0.0-dev sdk

chopper/lib/src/base.dart, chopper/lib/src/interceptor.dart, chopper/pubspec.yaml, chopper/test/converter_test.dart, chopper_generator/pubspec.yaml, example/bin/main_built_value.dart, example/bin/main_jaguar_serializer.dart, example/bin/main_json_serializable.dart, example/lib/built_value_resource.dart, example/lib/jaguar_serializer.chopper.dart, example/lib/jaguar_serializer.dart, example/lib/json_serializable.chopper.dart, example/lib/json_serializable.dart
I have just faced the issue, that if you want to convert Response from JSON string to a `List` of objects, you can not do it because converter _does not know_ about the `Body` type, and request fails on converting. 
``` 
Future<Response<Body>> _decodeResponse<Body, ToDecode>(...) async {
...
final converted = await withConverter.convertResponse<ToDecode>(response);
...
return converted;
}
```
`Unhandled Exception: type 'Response<dynamic>' is not a subtype of type 'FutureOr<Response<List<Language>>>'`
You can play with this types, but in this case without extra generic type you cannot get working program
The main idea of solution - just to add `ResultType` to converters with renaming `ToDecode` to `ItemType`
In `Converter`:
`convertResponse<ToDecode> => convertResponse<ResultType, …
=> Converter types fix

chopper/CHANGELOG.md, chopper/lib/src/base.dart, chopper/lib/src/interceptor.dart, chopper/lib/src/request.dart, chopper/lib/src/response.dart, chopper/lib/src/utils.dart, chopper/pubspec.yaml, chopper/test/base_test.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service.dart, example/web/main.dart
For usage just pass a `Stream<List<int>>` as a body for requests, or specify `Response<Stream<List<int>>>` as a return type in your generator to get a stream.
=> Add stream support for body request and for output body response

README.md, chopper/README.md
Replaces hardcoded version values such as `^2.0.0` with `^[latest version]` to help users avoid unintentionally grabbing older versions.
I'm submitting this PR after spending more than an hour trying to figure out why my types were being generated incorrectly and after finally figuring out the package was actually at 2.4.2 and not 2.0.0. Sure, it is also my fault for not paying enough attention, but it happens.
**EDIT:** Scratch that. I realize now that pub actually does get the latest version and the issue I'm facing seems to be unrelated. Regardless, I feel this might be an appropriate change considering it looks like the versions in the README are lagging, so I will be waiting for input before closing.
=> Use "latest version" instead of hardcoded values in README

chopper/lib/src/base.dart, chopper/lib/src/interceptor.dart, chopper/test/interceptors_test.dart
The current version of the `ResponseInterceptorFunc` did not allow me to use the `BodyType` in the actual interceptor because of how the typedef was done.
I also added the `DynamicResponseInterceptorFunc` such that old code that was using the interceptor without `BodyType` will keep working as expected
Note: it might be nice if in the future we also integrate the `BodyType` into the `onResponse` method of the `ResponseInterceptor` class
=> Add ability to use the BodyType in response interceptor

chopper/lib/src/annotations.dart, chopper_generator/lib/src/generator.dart
Add an `optionalBody` parameter to the `Post`, `Patch` and `Put` annotations to allow suppressing the warning for missing bodies in these requests.
The parameter defaults to `true` for all other HTTP methods.
Fixes #149
=> Add optionalBody parameter to suppress warnings

getting-started.md, interceptors.md
Fixing a minor typo in the docs, also I had issues with defining the interceptors the way the docs suggested. I had to define the type of the lambda parameter, also it looks like `Response` class has no `copyWith(...)` method, but has a `replace(..)` one.
=> Fix typo and invalid code sample in documentation

chopper_generator/lib/src/generator.dart
e.g.:
```
@Post(path: URL.DOCUMENT_PRIOR_INFO)
Future<Response<T>> getPriorInfo<T>(@Body() Params params);
```
Which is usefull when single API method may respond differently
depending on request parameter values.
=> This allows chopper API methods with generic attributes

chopper/lib/src/constants.dart, chopper/lib/src/interceptor.dart
Fix https://github.com/lejard-h/chopper/issues/179
Adds to the decode process to support two content-types:
- `application/json`
- `application/vnd.api+json`
Im not sure if I should add it to the encode function also.
I made a new PR *again* (https://github.com/lejard-h/chopper/pull/184) because the last one was opened from master and not from `develop` branch.
BTW is there any chance that you add a label hacktoberfest-accepted to this PR so it counts for this https://hacktoberfest.digitalocean.com ?
=> Add suport for JsonApi utf8 serialization

chopper/lib/src/authenticator.dart, chopper/lib/src/base.dart
An attempt to solve https://github.com/lejard-h/chopper/issues/47
Inspired by OkHTTP's [authenticator](https://github.com/square/okhttp/blob/480c20e46bb1745e280e42607bbcc73b2c953d97/okhttp/src/main/kotlin/okhttp3/Authenticator.kt)
The idea is to provide a reactive authentication in the event that an auth challenge is raised. It returns a nullable Request that contains a possible update to the original Request to satisfy the authentication challenge.
e.g. a request is made to a server that responses with a 401. The authenticator can be implemented however needed to update the original request, such as using a refresh token, then pass a new request back to be executed.
=> Implement authenticator

chopper/lib/src/interceptor.dart
Prints the Curl URL wrapped with double-quotes.
A super small change but extremely helpful.
It fixes issues when pasting the resulting log to the command line, where the curl request in some cases would not be closed by the terminal or fail to execute.
This is also the default behavior for the OkHttp Interceptor:
https://github.com/mrmike/Ok2Curl/blob/master/ok2curl/src/main/java/com/moczul/ok2curl/CurlBuilder.java#L27
=> Add double quotes to url in CurlInterceptor log

chopper/CHANGELOG.md, chopper/lib/src/annotations.dart, chopper/lib/src/request.dart, chopper/lib/src/response.dart, chopper/pubspec.yaml
- Remove deprecated `FileField`, use `PartFile` instead
- Remove deprecated `Request.replace`, use `Request.copyWith` instead
- Remove deprecated `PartValue.replace`, use `PartValue.copyWith` instead
- Remove deprecated `Response.replace`, use `Response.copyWith` instead
=> Cleanup deprecated

chopper/lib/src/authenticator.dart, chopper/lib/src/base.dart
As pointed out in the comments of #198, the Authenticator implementation went wrong along the way to null safety migration.
This PR attempts to fix that.
=> Fix infinite loop when using Authenticators

chopper/CHANGELOG.md, chopper/pubspec.yaml, chopper_generator/CHANGELOG.md, chopper_generator/pubspec.yaml
Fixes for #259 and #262 
@YoussefRaafatNasry
@imatok
Big thanks!
=> 4.0.1 fixes

chopper_generator/pubspec.yaml
Because json_serializable 5.0.0 depends on analyzer ^2.0.0 and chopper_generator >=4.0.1 depends on analyzer ^1.2.0 there is a version solving conflict that avoid using latest version of json_serializable.
=> analyzer dependency upgraded

chopper_generator/lib/src/generator.dart
For some reason `parts` items of type `PartValueFile` considered as non-nullable by default.
In `PartValueFile` implementation I am not seeing any constraints on inner value nullability.
`toMultipartRequest` method can throw out null values parts.
So I think we can make `parts` items of type `PartValueFile` support nullable inner values.
Fixes #288
=> fix(generator): fix PartValueFile value not nullable if arg is (#288)

chopper/lib/src/response.dart
=> fix: fix this.body cast of null value when response body is null (#291)

chopper/lib/src/base.dart
There is double processing when you've got your authenticator call. It leads to exceptions like "BuiltList<YourType> is not a String" or something. 
https://github.com/lejard-h/chopper/issues/259 contains the same behavior description.
=> Prevent double call on token refreshment

chopper/CHANGELOG.md, chopper/lib/src/base.dart, chopper/lib/src/response.dart, chopper/lib/src/utils.dart, chopper/pubspec.yaml, chopper_generator/CHANGELOG.md, chopper_generator/lib/chopper_generator.dart, chopper_generator/lib/src/generator.dart, chopper_generator/pubspec.yaml
Co-authored-by: Ivan Terekhin <i.terhin@gmail.com>
Co-authored-by: Youssef Raafat <youssefraafatnasry@gmail.com>
=> Release 4.0.3

chopper_generator/lib/src/generator.dart
This PR adds `unnecessary_brace_in_string_interps` to the list of lint ignores for generated files.
https://github.com/lejard-h/chopper/pull/275 is the source of the issue, however it's difficult to determine when the braces are necessary.
=> Add unnecessary_brace_in_string_interps to lint ignores

chopper/lib/src/authenticator.dart, chopper/lib/src/base.dart
Fix `_handleRequestConverter` getting called twice if using an authenticator with a `JsonConverter` on the request.
Otherwise an already encoded body string in `req.body` will be encoded again after the authentication challenge was solved.
So in the end in this MR we call `send()` with the same arguments as the initial request which fails with 403 as the token is outdated.
This behaviour was last changed in #310 to fix #308.
=> Fix converter getting called twice if using an authenticator with a JsonConverter on the request

chopper/example/definition.chopper.dart, chopper/test/base_test.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service.dart, chopper_generator/lib/src/generator.dart
This addresses https://github.com/lejard-h/chopper/issues/343
I've used [Expression.ifNullThen](https://pub.dev/documentation/code_builder/latest/code_builder/Expression/ifNullThen.html) to additionally check for a nullable `QueryMap`.
This should be able to take
```dart
@Get(path: 'query_map')
Future<Response> getQueryMapTest4({
@Query('name') String name = '',
@Query('number') int? number,
@QueryMap() Map<String, dynamic>? filters, // <-- nullable / optional filters
});
```
and generate
```dart
@override
Future<Response<dynamic>> getQueryMapTest4(
{String name = '', int? number, Map<String, dynamic>? filters}) {
final $url = '/test/query_map';
final $params = <String, dynamic>{'name': name, 'number': number};
$params.addAll(filters ?? {}); // <-- because Map.addAll expects a …
```
=> Fix nullable QueryMap fails to compile

chopper/lib/src/interceptor.dart, chopper/test/converter_test.dart, chopper_built_value/lib/chopper_built_value.dart, chopper_built_value/test/converter_test.dart, chopper_generator/pubspec.yaml, example/bin/main_built_value.dart, example/bin/main_json_serializable.dart
This partially addresses https://github.com/lejard-h/chopper/issues/158 and is mostly based on @lejard-h's suggestion https://github.com/lejard-h/chopper/issues/158#issuecomment-678760392
**This is a breaking change** as it changes the response types of some `JsonConverter` methods, namely:
- `decodeJson` now returns `FutureOr<Response>`
```dart
/// before
Response decodeJson<BodyType, InnerType>(Response response) {
/* sync decode stuf */
}
/// after
FutureOr<Response> decodeJson<BodyType, InnerType>(Response response) async {
/* async decode stuff */
}
```
- `convertResponse` now returns `FutureOr<Response<BodyType>>`
```dart
/// before
@override
Response<BodyType> convertResponse<BodyType, InnerType>(Response response) {
/* sync convert stuff */
}
/// after
@override …
```
=> Change return type of decodeJson to FutureOr in order to be able to support compute()

chopper_generator/lib/src/generator.dart, chopper_generator/pubspec.yaml
[As mentioned previously](https://github.com/lejard-h/chopper/pull/345#issuecomment-1193179037) I had to pin [`analyzer`](https://github.com/dart-lang/sdk/tree/main/pkg/analyzer) to `>=4.1.0 <4.3.0`.
The issue is that [`analyzer`](https://github.com/dart-lang/sdk/tree/main/pkg/analyzer) deprecated [`Element.enclosingElement`](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/CHANGELOG.md#430) which is being used in [chopper_generator](https://github.com/lejard-h/chopper/blob/master/chopper_generator/lib/src/generator.dart#L343) and that caused the tests to fail because of a linter warning. 🚨
This change inadvertently affects users of [`mockito`](https://github.com/dart-lang/mockito), which has to be pinned to `>=5.2.0 <5.3.0` to circumvent this small issue.
I have now reverted …
=> Revert analyzer to ^4.1.0 and silence linters for Element.enclosingElement

.github/ISSUE_TEMPLATE/bug_report.md
I added a Github issue template to streamline bug reports.
It's essentially a carbon copy of the [template Flutter uses](https://github.com/flutter/flutter/blob/master/.github/ISSUE_TEMPLATE/2_bug.md). 🤓
I left the `assignees` field empty, because I'm not sure who should triage them.
@JEuler / @stewemetal  thoughts?
=> Add Bug Report Github issue template

chopper/example/definition.chopper.dart, chopper/test/test_service.chopper.dart, chopper_generator/lib/src/generator.dart, example/lib/built_value_resource.chopper.dart, example/lib/json_serializable.chopper.dart
While I was migrating `expression.assignFinal(name)` to `declareFinal(name).assign(expression)` I noticed that I could also add types in there, however, it did not feel appropriate for the PR https://github.com/lejard-h/chopper/pull/358.
So, I'm adding them here, which in essence makes code like this
```dart
@override
Future<Response<String>> getTest(
String id, {
required String dynamicHeader,
}) {
final $url = '/test/get/${id}';
final $headers = {
'test': dynamicHeader,
};
final $request = Request(
'GET',
$url,
client.baseUrl,
headers: $headers,
);
return client.send<String, String>($request);
}
```
look like
```dart
@override
Future<Response<String>> getTest(
String id, {
required String dynamicHeader,
}) {
final String $url = '/test/get/${id}';
final Map<String, String> $headers = { …
```
=> [chopper_generator] Add types to the generated variables

example/bin/main_json_serializable_squadron_worker_pool.dart, example/lib/json_decode_service.activator.g.dart, example/lib/json_decode_service.dart, example/lib/json_decode_service.vm.g.dart, example/lib/json_decode_service.worker.g.dart, example/pubspec.yaml, faq.md
This is a follow-up on https://github.com/lejard-h/chopper/issues/158#issuecomment-1245991530
Since wiring all this up isn't really that straightforward, I decided to write an example using:
- [json_serializable](https://github.com/google/json_serializable.dart)
- [squadron](https://github.com/d-markey/squadron)
- [squadron_builder](https://github.com/d-markey/squadron_builder)
Essentially all one needs to do is:
1. install the dependencies: `dart pub add squadron squadron_builder`
2. make a service like `example/lib/json_decode_service.dart`
3. run code generation: `dart run build_runner build`
4. wire up `example/lib/json_decode_service.dart` with a custom `JsonConverter`
5. configure and start a `WorkerPool`
6. run HTTP requests like a boss using Isolate Workers 😎
=> Provide an example using an Isolate Worker Pool with Squadron

chopper/lib/chopper.dart, chopper/lib/src/annotations.dart, chopper/lib/src/base.dart, chopper/lib/src/constants.dart, chopper/lib/src/extensions.dart, chopper/lib/src/interceptor.dart, chopper/lib/src/request.dart, chopper/pubspec.yaml, chopper/test/base_test.dart, chopper/test/extensions_test.dart, chopper/test/interceptors_test.dart, chopper/test/multipart_test.dart, chopper/test/request_test.dart, chopper_built_value/test/converter_test.dart
I think that [`Request`](https://github.com/lejard-h/chopper/blob/master/chopper/lib/src/request.dart#L11) should inherit from [`BaseRequest`](https://pub.dev/documentation/http/latest/http/BaseRequest-class.html).
The added benefit of this is that `Request` ceases to be a Chopper-specific class and now behaves like a `BaseRequest`. 
The only downside is that `Request` can no longer be immutable and have a `const` constructor as `BaseClass` and all its children also aren't immutable and don't have `const` constructors.
```dart
class Request extends http.BaseRequest {
/// I renamed this to [path] because it is essentially the same as [Uri.path]
final String path;
/// I renamed this to [origin] because it is essentially the same as [Uri.origin]
final String origin;
final dynamic body;
final …
```
=> Request extends http.BaseRequest

chopper/lib/src/annotations.dart, chopper/lib/src/request.dart, chopper/lib/src/utils.dart, chopper/test/base_test.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service.dart, chopper/test/utils_test.dart, chopper_generator/analysis_options.yaml, chopper_generator/lib/src/generator.dart
Fix #371 
Because some backends do not ignore `null` query parameters I have re-introduced the behaviour of excluding `null` query vars by default. This includes nested `null` query parameters inside maps.
This was the default behaviour prior to `v5.0.1` and the merge of https://github.com/lejard-h/chopper/pull/364.
Additionally, I have added a `@Method` annotation `bool includeNullQueryVars` which, if set to `true`, includes `null` query parameters when encoding them into the URL query. 
- Example with `includeNullQueryVars: false` (default; same behaviour as before `v5.0.1`)
```dart
@Get(path: '/get_data')
Future<Response<String>> getData({
@Query('foo') String? foo,
@Query('bar') String? bar,
@Query('baz') String? baz,
});
final response = await service.getData(
foo: 'foo_val',
baz: …
```
=> Exclude null query vars by default and add new @Method annotation includeNullQueryVars

.github/workflows/dart.yml, .github/workflows/publish.yml, mono_repo.yaml, tool/ci.sh
This will resolve the Node 12 deprecation warning
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/cache, actions/checkout, actions/checkout, actions/cache
Read more [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
=> [workflow] Upgrade mono_repo to v6.4.1

chopper_generator/pubspec.yaml
Addresses https://github.com/lejard-h/chopper/issues/377
I think that bumping it up to `^5.0.0` is a bit harsh [because that version removed quite a few deprecated APIs](https://pub.dev/packages/analyzer/changelog#500). It would probably also warrant a minor version release rather than just a patch release, so I went with `analyzer: '>=4.4.0 <6.0.0'` which should give users a gentler transition.
=> Update analyzer to >=4.4.0 <6.0.0

chopper/example/definition.chopper.dart, chopper/example/main.dart, chopper/lib/src/base.dart, chopper/lib/src/request.dart, chopper/test/base_test.dart, chopper/test/client_test.dart, chopper/test/converter_test.dart, chopper/test/interceptors_test.dart, chopper/test/multipart_test.dart, chopper/test/request_test.dart, chopper/test/test_service.chopper.dart, chopper_built_value/test/converter_test.dart, chopper_generator/lib/src/generator.dart, example/bin/main_built_value.dart, example/bin/main_json_serializable.dart, example/bin/main_json_serializable_squadron_worker_pool.dart, example/lib/built_value_resource.chopper.dart, example/lib/json_serializable.chopper.dart, faq.md
I took the liberty of replacing the `String` based url path in the client calls with an `Uri` as request in the #304 feature request.
This is now more in line with the underlying `Http.Client`. 
Any feedback is welcome :)
=> [Feature] Replace the String based path with Uri

faq.md
I've seen at least 3 issues related to setting up the [Authenticator](https://github.com/lejard-h/chopper/blob/develop/chopper/lib/src/authenticator.dart).
Digging out an example from https://github.com/lejard-h/chopper/pull/198#issuecomment-761781430 is just too cumbersome, so I've added an entry into the FAQ.
=> :memo: Add Authenticator example

chopper/lib/src/base.dart, chopper/test/authenticator_test.dart, chopper/test/fake_authenticator.dart
This fixes #388
When `ChopperClient` is configured with an `Authenticator` and when `Authenticator.authenticate` returns a non-null value, `ChopperClient.send` recursively passes an already converted `Request` to `ChopperClient.send` again. This results in double-encoded JSON.
```
Expected: '{"name":"john","surname":"doe"}'
Actual: '"{\\"name\\":\\"john\\",\\"surname\\":\\"doe\\"}"'
Which: is different.
Expected: {"name":"j ...
Actual: "{\\"name\ ...
^
Differ at offset 0
```
As previously mentioned, the issue only manifests itself when`Authenticator.authenticate` returns a non-null value, in essence when the client receives an `HTTP ERROR: 401`. It works perfectly fine when the client is authenticated and/or the Auth token hasn't expired. That's why it probably flew under the radar for so …
=> Fix #388 Triggering Authenticator double encodes body in POST, PUT, PATCH

chopper/pubspec.yaml, chopper/test/multipart_test.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service.dart
Used [kTransparentImage](https://pub.dev/packages/transparent_image) for an image upload test.
This should shine a light on #384
=> Add image upload test

chopper/lib/chopper.dart, chopper/lib/src/http_logging_interceptor.dart, chopper/lib/src/interceptor.dart, chopper/test/http_logging_interceptor_test.dart, chopper/test/interceptors_test.dart, interceptors.md
Updated the `HttpLoggingInterceptor` so users can specify a more fine grained logging level for there needs.
Inspired by the `HttpLoggingInterceptor` configuration of OkHttp.
=> Configurable HttpLoggingInterceptor

chopper/lib/src/utils.dart, chopper/test/converter_test.dart, chopper/test/utils_test.dart
Fixes #398
`applyHeaders` would override headers with different cases. But the header field names should be case-insensitive according to the [RFC 7540](https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2).
This MR makes applying headers case insensitive. Also added bunch of tests for verifying `applyHeaders`.
=> Made apply headers field name case insensitive.

chopper/lib/src/annotations.dart, chopper/lib/src/utils.dart
I noticed that some code inside comment blocks (`///`) was annotated to start with ` ```dart ` but didn't end with ` ``` `.
As a result, the code wasn't properly highlighted on Github, for example [here](https://github.com/lejard-h/chopper/blob/develop/chopper/lib/src/annotations.dart#L330).
**NOTE** this is a cosmetic fix only. No code was changed, only comments.
=> :bulb: Clean up code in comments

faq.md
The MockClient documentation link was dead, and so I've updated it and included a link to the http.testing library documentation.
=> Fix dead link on FAQs page

chopper_built_value/pubspec.yaml
Updated `chopper_built_value` chopper version to `6.0.0`. As mentioned in #405
=> Updated chopper version to 6.0.0 for chopper_built_value

.github/CODEOWNERS
Addresses #413
Currently adds these as **global** [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners):
* @Guldem 
* @JEuler 
* @lejard-h 
* @meysam1717
* @pixeltoast 
* @stewemetal 
* @techouse
Anyone else who wants to be added or wants to be removed from this preliminary list, please post a comment below.
=> :construction_worker: add CODEOWNERS

.github/workflows/publish.yml
Fixes https://github.com/lejard-h/chopper/pull/420#issuecomment-1546819753
Instead of
```bash
echo '${{ secrets.PUB_CREDENTIALS }}' > "$XDG_CONFIG_HOME/dart/pub-credentials.json"
```
it should be
```bash
echo '${{ secrets.CREDENTIAL_JSON }}' > "$XDG_CONFIG_HOME/dart/pub-credentials.json"
```
=> :green_heart: Fix CI publish credentials

.github/workflows/publish.yml, chopper_generator/lib/src/generator.dart
In the previous PR https://github.com/lejard-h/chopper/pull/424 I forgot that the `publish.yaml` workflow does not operate from a pull request but directly on the master branch. That will obviously fail to acquire the previous version. To fix it I changed the checkout process to checkout the master from 1 commit before (`HEAD^`).
```yaml
- id: checkout
uses: actions/checkout@v3
with:
fetch-depth: 2
- run: git checkout HEAD^
```
=> :green_heart: fix publish workflow

.github/workflows/publish.yml, chopper_generator/lib/src/generator.dart
Merge https://github.com/lejard-h/chopper/pull/427 into master
=> :twisted_rightwards_arrows: merge publish workflow fix to master

chopper/lib/src/request.dart
Currently `followRedirects` are not passed to `http.Request` in this method `toHttpRequest`. This causes setting `followRedirects` to `false` for example in a interceptor to not be passed http client.
=> Adding follow redirects to toHttpRequest

example/build.yaml, example/lib/json_decode_service.vm.g.dart, example/lib/json_decode_service.worker.g.dart, example/pubspec.yaml
Update the example using [squadron](https://pub.dev/packages/squadron).
When upgrading squadron and squadron_builder one has to add this to `build.yml`
```yaml
squadron_builder:worker_builder:
options:
with_finalizers: true
serialization_type: List
```
Relates to https://github.com/d-markey/squadron/issues/19
=> :arrow_up: update squadron example

chopper/pubspec.yaml, chopper_built_value/pubspec.yaml
[http](https://pub.dev/packages/http) recently got bumped to `v1.0.0` and since it's backwards compatible with `v0.13.0` we should bump the constraint
=> :arrow_up: update http constraint to ">=0.13.0 <2.0.0"

chopper/lib/src/interceptor.dart, chopper/test/interceptors_test.dart
When using CurlInterceptor, the log output for MultipartRequest was missing. So, I added the Log of MultipartRequest. :)
=> Add MultipartRequest log to CurlInterceptor

.github/workflows/publish.yml
To keep the credentials safe, I added a `cleanup` step that deletes the credentials file and **always** runs at the end of the `publish` workflow.
```yml
- name: Cleanup
id: cleanup
if: ${{ always() }}
run: |
rm -rf "$XDG_CONFIG_HOME/dart/pub-credentials.json"
```
=> :green_heart: add cleanup step to publish workflow

chopper/CHANGELOG.md, chopper/pubspec.yaml, chopper_built_value/CHANGELOG.md, chopper_built_value/pubspec.yaml, chopper_generator/CHANGELOG.md, example/pubspec.yaml
Sync the versions and changelogs of origin/master with origin/develop
=> :twisted_rightwards_arrows: post release branch sync

chopper_generator/lib/chopper_generator.dart, chopper_generator/lib/src/generator.dart
Give the user the option for generating files in different directories, just as [described here](https://pub.dev/packages/source_gen#generating-files-in-different-directories).
Example of a `build.yml` that will put `*.chopper.dart` files in a custom `lib/generated` directory
```yaml
targets:
$default:
builders:
chopper_generator:
options:
build_extensions:
'^lib/{{}}.dart': 'lib/generated/{{}}.chopper.dart'
```
---
Addresses #443
=> :sparkles: Generating files in different directories

.github/workflows/dart.yml, chopper/pubspec.yaml, chopper/test/ensure_build_test.dart, chopper_generator/Makefile, chopper_generator/README.md, chopper_generator/lib/chopper_generator.dart, chopper_generator/lib/src/builder_factory.dart, chopper_generator/lib/src/extensions.dart, chopper_generator/lib/src/generator.dart, chopper_generator/lib/src/utils.dart, chopper_generator/lib/src/vars.dart, chopper_generator/mono_pkg.yaml, chopper_generator/pubspec.yaml, chopper_generator/test/ensure_build_test.dart, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service.dart
=> :recycle: refactor chopper_generator

.github/workflows/dart.yml, chopper/pubspec.yaml, chopper/test/ensure_build_test.dart, chopper_generator/CHANGELOG.md, chopper_generator/Makefile, chopper_generator/README.md, chopper_generator/lib/chopper_generator.dart, chopper_generator/lib/src/builder_factory.dart, chopper_generator/lib/src/extensions.dart, chopper_generator/lib/src/generator.dart, chopper_generator/lib/src/utils.dart, chopper_generator/lib/src/vars.dart, chopper_generator/mono_pkg.yaml, chopper_generator/pubspec.yaml, chopper_generator/test/ensure_build_test.dart, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service.dart
=> :bookmark: release chopper generator v6.0.3

chopper/lib/src/annotations.dart, chopper/lib/src/base.dart, chopper/lib/src/constants.dart, chopper/lib/src/http_logging_interceptor.dart, chopper/lib/src/interceptor.dart, chopper/lib/src/request.dart, chopper/lib/src/response.dart, chopper/lib/src/utils.dart, chopper/pubspec.yaml, chopper/test/fixtures/http_response_fixture.dart, chopper/test/fixtures/payload_fixture.dart, chopper/test/fixtures/request_fixture.dart, chopper/test/fixtures/response_fixture.dart, chopper/test/helpers/payload.dart, chopper_built_value/pubspec.yaml, chopper_generator/lib/src/generator.dart, chopper_generator/lib/src/utils.dart, chopper_generator/pubspec.yaml, example/pubspec.yaml
- bump minimum Dart SDK version to 3.0.0
- bump dependencies to the latest (except `analyzer`)
- implement [Dart 3 class modifiers](https://dart.dev/language/class-modifiers)
- bump all package major versions:
- chopper: 7.0.0
- chopper_generator: 7.0.0
- chopper_built_value: 2.0.0
=> :sparkles: implement Dart 3 class modifiers

.github/CODEOWNERS
Fixes these 2 [CODEOWNERS](https://github.com/lejard-h/chopper/blob/develop/.github/CODEOWNERS) errors:
* Unknown owner on line 5: make sure @Guldem exists and has write access to the repository
* Unknown owner on line 5: make sure @pixeltoast exists and has write access to the repository
=> :passport_control: fix CODEOWNERS

chopper/example/definition.chopper.dart, chopper/test/test_service.chopper.dart, chopper_generator/lib/src/generator.dart, chopper_generator/test/test_service.chopper.dart, example/lib/built_value_resource.chopper.dart, example/lib/json_serializable.chopper.dart
This PR adds the [`final` class modifier](https://dart.dev/language/class-modifiers#final) to the generated Chopper API implementation, i.e.
**before**
```dart
class _$MyService extends MyService {
_$MyService([ChopperClient? client]) {
if (client == null) return;
this.client = client;
}
// ... stuff
}
```
**after**
```dart
final class _$MyService extends MyService {
_$MyService([ChopperClient? client]) {
if (client == null) return;
this.client = client;
}
// ... stuff
}
```
=> :sparkles: add final class modifier to generated Chopper API implementation

.github/workflows/dart.yml, chopper/CHANGELOG.md, chopper/example/definition.chopper.dart, chopper/lib/src/base.dart, chopper/lib/src/interceptor.dart, chopper/lib/src/utils.dart, chopper/pubspec.yaml, chopper/test/base_test.dart, chopper/test/test_service.chopper.dart, chopper_built_value/mono_pkg.yaml, chopper_generator/CHANGELOG.md, chopper_generator/lib/src/generator.dart, chopper_generator/mono_pkg.yaml, chopper_generator/pubspec.yaml, chopper_generator/test/test_service.chopper.dart, example/lib/built_value_resource.chopper.dart, example/lib/json_serializable.chopper.dart, mono_repo.yaml, tool/ci.sh
- Refactor ChopperClient constructor
- Refactor ChopperClient.getService
- Refactor CurlInterceptor
- Add final class modifier to generated Chopper API implementation
=> :bookmark: release v7.0.1

chopper/lib/src/http_logging_interceptor.dart
This function can then be overridden to use alternative logging implementations besides the default flutter logging.
This can be especially useful if you want to only write one (multiline) log entry per request, instead of one entry per line.
=> :sparkles: HttpLoggingInterceptor: allow to pass custom logger

chopper/lib/src/chopper_log_record.dart, chopper/lib/src/http_logging_interceptor.dart
=> :sparkles: Attach request/response to interceptor log lines

chopper/lib/chopper.dart
Forgot to do this is my last PR.
=> :adhesive_bandage: export ChopperLogRecord to library surface

chopper_generator/pubspec.yaml
Change the `analyzer` constraint of `chopper_generator` to
```yaml
analyzer: ">=5.13.0 <7.0.0"
```
in order to allow a more graceful transition.
---
Supersedes https://github.com/lejard-h/chopper/pull/474
=> :arrow_up: allow chopper_generator to use analyzer v6

chopper_generator/CHANGELOG.md, chopper_generator/pubspec.yaml
=> :bookmark: release chopper_generator v7.0.2

chopper/lib/src/annotations.dart, chopper/test/base_test.dart, chopper/test/ensure_build_test.dart, chopper/test/test_service_variable.chopper.dart, chopper/test/test_service_variable.dart, chopper_generator/lib/src/generator.dart, chopper_generator/test/ensure_build_test.dart, chopper_generator/test/test_service_variable.chopper.dart, chopper_generator/test/test_service_variable.dart
I created this pr to give support to top level variables for the scenarios where we have multiple urls and that urls depend on ambient. for example we have our service A to make the main requests but we have service B to specific funcionality with diferent base url and maybe we want to change the service B to a dev version, so to change the url we have tu rebuild the chopper files because base url points to the literal value of the variable, with this change we don't need to rebuild in that scenerio because we can point the base url to a top level variable and that variable is going to be present in the generated file instead of the literal value
Imaging this case
```dart
const String enviromentUrl = Enviroments.temporal;
class Enviroments {
static const String temporal = …
```
=> Adding support for top level variables

chopper/lib/src/base.dart, chopper/lib/src/interceptor.dart, chopper/test/converter_test.dart
Fixes #492
Also fixes #388 and properly implements #390 by checking if the `request.body` is already a JSON before encoding it to JSON thereby preventing duplicate JSON encoding when using the `authenticator`.
=> :bug: fix chopper base.dart send() authenticate sending wrong request

.github/workflows/publish.yml, .github/workflows/publish_dry_run.yml, chopper_built_value/CHANGELOG.md, chopper_built_value/pubspec.yaml
Fixes
```
Invalid `topics` value (`built_value`): must consist of lowercase alphanumerical characters or dash (but no double dash), starting with a-z and ending with a-z or 0-9.
```
Looks like the topic `built_value` has to be renamed to `built-value` 😒 Odd that `dart pub publish --dry-run` didn't catch it.
To prevent this in the future, I've added a step into both the `publish.yml` and `publish_dry_run.yml` workflows:
```yaml
- name: Validate pub.dev topics
id: validate_pub_dev_topics
run: |
set -e
pushd ${{ matrix.package }} || exit
pattern="^[a-z][a-z0-9-]*[a-z0-9]$"
for topic in $(yq -r '.topics[]' pubspec.yaml); do
if [[ ! $topic =~ $pattern ]]; then
echo "Invalid topic: $topic"
exit 1
fi
done
popd || exit
```
=> :bug: Fix chopper_built_value pub.dev topics

chopper/example/definition.chopper.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service_variable.chopper.dart, chopper_generator/lib/src/generator.dart, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service_variable.chopper.dart
=> :rotating_light: ignore unnecessary_string_interpolations

chopper/lib/src/utils.dart, chopper/test/base_test.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service.dart
=> :sparkles: encode DateTime query parameters as ISO8601

chopper/CHANGELOG.md, chopper/test/base_test.dart, chopper/test/ensure_build_test.dart, chopper/test/test_service_base_url.chopper.dart, chopper/test/test_service_base_url.dart, chopper_generator/lib/src/generator.dart
I rewrite the replaceallMethod that removes double ```//``` making it follow a regular expresion that ignores ```http://``` and ```https://``` on the replacement
---
Addresses #519
=> Fix incorrect url generation when using new baseurl

chopper/lib/src/authenticator.dart, chopper/lib/src/base.dart, chopper/test/authenticator_test.dart, chopper/test/fake_authenticator.dart
=> Added success/failure callback hooks to Authenticator.

chopper/Makefile, chopper_built_value/Makefile
Force `lcov` to ignore unused patterns.
=> :bug: fix Makefile show_test_coverage

chopper/CHANGELOG.md, chopper/Makefile, chopper/lib/src/authenticator.dart, chopper/lib/src/base.dart, chopper/lib/src/chopper_log_record.dart, chopper/lib/src/request.dart, chopper/lib/src/response.dart, chopper/pubspec.yaml, chopper/test/authenticator_test.dart, chopper/test/fake_authenticator.dart, chopper_built_value/Makefile, chopper_built_value/pubspec.yaml, chopper_generator/pubspec.yaml
- Add success/failure callback hooks to Authenticator ([#527](https://github.com/lejard-h/chopper/pull/527))
- Add mock mixins of Chopper components ([#529](https://github.com/lejard-h/chopper/pull/529))
=> :bookmark: release chopper v7.0.9

chopper/example/definition.chopper.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service_base_url.chopper.dart, chopper/test/test_service_variable.chopper.dart, chopper_generator/lib/src/generator.dart, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service_variable.chopper.dart
I scanned through the generator again and refactored some bits and pieces.
@JEuler let me know your thoughts on this.
=> :lipstick: cosmetic generator refactor

.github/workflows/dart.yml, .github/workflows/publish.yml, .github/workflows/publish_dry_run.yml, tool/ci.sh
=> :construction_worker: update CI

.github/workflows/dart.yml, .github/workflows/publish.yml, .github/workflows/publish_dry_run.yml, chopper/CHANGELOG.md, chopper/example/definition.chopper.dart, chopper/pubspec.yaml, chopper/test/base_test.dart, chopper/test/fixtures/example_enum.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service.dart, chopper/test/test_service_base_url.chopper.dart, chopper/test/test_service_variable.chopper.dart, chopper_generator/CHANGELOG.md, chopper_generator/lib/src/generator.dart, chopper_generator/pubspec.yaml, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service.dart, chopper_generator/test/test_service_variable.chopper.dart, tool/ci.sh
- Enable the user to specify non-String type header values by calling `.toString()` on any non-String Dart type. ([#538](https://github.com/lejard-h/chopper/pull/538))
- Enable the user to specify non-String type header values by calling `.toString()` on any non-String Dart type. ([#538](https://github.com/lejard-h/chopper/pull/538))
=> :bookmark: release chopper v7.0.10, chopper_generator v7.0.7

chopper/lib/src/response.dart, chopper/test/base_test.dart, chopper/test/fixtures/error_fixtures.dart
Added simple helper function for fetching error of a specific type. This could be helpful when a error converter is added to convert error into a custom error object. This reduces the boilerplate needed to get the custom error from the response.
See #429
=> Helper function for fetching errors of specific type

chopper/lib/src/chopper_http_exception.dart, chopper/lib/src/response.dart, chopper/test/base_test.dart, chopper/test/chopper_http_exception_test.dart, chopper/test/ensure_build_test.dart, chopper/test/response_test.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service.dart, chopper/test/test_service_variable.chopper.dart, chopper/test/test_without_response_service.chopper.dart, chopper/test/test_without_response_service.dart, chopper_generator/lib/src/generator.dart, chopper_generator/lib/src/vars.dart, chopper_generator/test/ensure_build_test.dart, chopper_generator/test/test_service.dart, chopper_generator/test/test_service_variable.chopper.dart, chopper_generator/test/test_service_variable.dart, chopper_generator/test/test_without_response_service.chopper.dart, chopper_generator/test/test_without_response_service.dart
Added the possibility to omit Response when creating a service to reduce some boilerplate if the Response object is not really needed.
This give the developer the choice to make use of the Response and its meta data is needed. This might not always be case because a error converter deals with the error logic. 
**TODO**:
Update documentation for this feature
Previously a `ChopperService` was created like this (still valid):
```dart
@ChopperApi(baseUrl: '/test')
abstract class MyChopperService extends ChopperService {
static MyChopperService create([ChopperClient? client]) =>
_$MyChopperService(client);
@Get(path: 'get/{id}')
Future<Response<String>> getSomething(
@Path() String id, {
@Header('test') required String dynamicHeader,
});
}
```
Which creates:
```dart
final class …
```
=> :sparkles: Feature: Omit Response in service

chopper/lib/src/annotations.dart, chopper/lib/src/http_logging_interceptor.dart, chopper/lib/src/interceptor.dart, chopper/lib/src/request.dart, chopper/lib/src/response.dart, faq.md, getting-started.md, requests.md
- Added/Updated documentation with new `Response` omit functionality
- Updated/Improved `request.md` documentation
- Added dartdoc `@template` to shared dartdoc between class and constructor for:
- HttpLoggingInterceptor
- HeadersInterceptor
- JsonConverter
- FormUrlEncodedConverter
- Request
-  Response
- All annotations
- Added const variants from all annotations. This make `@Get()` and `@get` both valid annotations.
- Added FAQ on using Chopper and Injectable together.
=> :memo: Improved documentation + added const annotations

chopper/test/test_service.chopper.dart, chopper/test/test_service.dart, chopper_generator/lib/src/generator.dart, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service.dart
=> :bug: fix chopper_generator regression introduced in #534

chopper/CHANGELOG.md, chopper/lib/src/annotations.dart, chopper/lib/src/chopper_http_exception.dart, chopper/lib/src/http_logging_interceptor.dart, chopper/lib/src/interceptor.dart, chopper/lib/src/request.dart, chopper/lib/src/response.dart, chopper/pubspec.yaml, chopper/test/chopper_http_exception_test.dart, chopper/test/ensure_build_test.dart, chopper/test/fixtures/error_fixtures.dart, chopper/test/response_test.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service.dart, chopper/test/test_service_variable.chopper.dart, chopper/test/test_service_variable.dart, chopper/test/test_without_response_service.chopper.dart, chopper/test/test_without_response_service.dart, chopper_generator/CHANGELOG.md, chopper_generator/lib/src/generator.dart, chopper_generator/lib/src/vars.dart, chopper_generator/pubspec.yaml, chopper_generator/test/ensure_build_test.dart, chopper_generator/test/test_service_variable.chopper.dart, chopper_generator/test/test_service_variable.dart, chopper_generator/test/test_without_response_service.chopper.dart, chopper_generator/test/test_without_response_service.dart, faq.md, getting-started.md, requests.md
- #545
- #543
- #548
- #545
- #549
=> :bookmark: release v7.1.0

chopper/CHANGELOG.md, chopper/pubspec.yaml
- Bump `chopper_generator` version requirement to 7.1.0
=> :bookmark: release chopper v7.1.0+1

chopper_generator/lib/src/builder_factory.dart, chopper_generator/pubspec.yaml, faq.md
Gives the user the ability to override the generated file extension from `.chopper.dart` to whatever they want, i.e. `.chopper.g.dart`.
To use this feature you have to create a `build.yaml` file in your project's root directory and add the following lines
```yaml
targets:
$default:
builders:
chopper_generator:
options:
build_extensions: {".dart": [".chopper.g.dart"]}
```
Note that using this feature means that you will **also** have to change the `part` declarations in your dart files, i.e.
from
```dart
part 'my_service.chopper.dart';
```
to
```dart
part 'my_service.chopper.g.dart';
```
---
Addresses #560
=> :sparkles: add option to override build_extension

faq.md
I somehow messed up the FAQ when doing the release. 🤪
=> :rewind: revert faq.md

chopper/lib/src/annotations.dart
Added `Target` annotations to chopper annotations to provide analysers and tooling with more information about the annotation placements.
=> :sparkles: Add Target annotations

.github/workflows/dart.yml
This reverts commit 3af6e4e06c35aa8768432e9ec3516de8cb9de9ad.
---
Codecov v4 requires a token and since I do not have permission to add a secret to this Github repository I'm reverting this commit by dependabot.
=> Revert ":arrow_up: Bump codecov/codecov-action from 3 to 4 (#571)"

chopper/lib/src/annotations.dart, chopper_generator/lib/src/generator.dart, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service.dart, requests.md
fix https://github.com/lejard-h/chopper/issues/577
* Support @FormUrlEncoded，
* auto add content-type application/x-www-form-urlencoded 
* set ket.toString and value.toString() for @Body / @Field / @FieldMap data,  if data is `Map` and  `Map` is not `Map<String, String>`
=> Support @FormUrlEncoded

chopper/lib/src/request.dart
sorry, i find a bug about `Request.copyWith`
=> :bug: fix Request.copyWith lose tag param

chopper/analysis_options.yaml, chopper/lib/chopper.dart, chopper/lib/src/annotations.dart, chopper/lib/src/list_format.dart, chopper/lib/src/request.dart, chopper/lib/src/utils.dart, chopper/pubspec.yaml, chopper/test/base_test.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service.dart, chopper/test/test_service_base_url.chopper.dart, chopper/test/test_service_base_url.dart, chopper/test/test_service_variable.chopper.dart, chopper/test/test_service_variable.dart, chopper/test/test_without_response_service.chopper.dart, chopper/test/test_without_response_service.dart, chopper/test/utils_test.dart, chopper_generator/analysis_options.yaml, chopper_generator/lib/src/generator.dart, chopper_generator/lib/src/utils.dart, chopper_generator/pubspec.yaml, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service.dart, chopper_generator/test/test_service_variable.chopper.dart, chopper_generator/test/test_service_variable.dart, chopper_generator/test/test_without_response_service.chopper.dart, chopper_generator/test/test_without_response_service.dart, example/analysis_options.yaml
@diegotori noticed that a `Map<String, dynamic>` like this
```dart
{
'filters': {
r'$or': [
{
'date': {
r'$eq': '2020-01-01',
}
},
{
'date': {
r'$eq': '2020-01-02',
}
}
],
'author': {
'name': {
r'$eq': 'Kai doe',
},
}
}
}
```
did not get encoded properly to
```
filters[$or][][date][$eq]=2020-01-01&filters[$or][][date][$eq]=2020-01-02&filters[author][name][$eq]=Kai%20doe
```
but became this
```
filters[$or][]={date: {$eq: 2020-01-01}}&filters[$or][]={date: {$eq: 2020-01-02}}&filters[author][name][$eq]=Kai doe
```
This PR fixes this by using an external library [qs_dart](https://pub.dev/packages/qs_dart) which is a Dart port of [qs](https://www.npmjs.com/package/qs) which I've been painstakingly working on over the past couple of weeks. 🤓
This now means that the output of Chopper, while …
=> :zap: use qs_dart for query string encoding

.github/workflows/dart.yml, .github/workflows/publish.yml, .github/workflows/publish_dry_run.yml
This should fix all the CI warnings like
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
=> :arrow_up: update Github actions

chopper/lib/src/annotations.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service.dart, chopper_generator/lib/src/generator.dart, chopper_generator/lib/src/utils.dart, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service.dart
This PR adds a new `timeout` annotation
```dart
/// Set a timeout for the request
final Duration? timeout;
```
that can be used like
```dart
@Get(path: 'get_timeout', timeout: Duration(seconds: 42))
Future<Response<String>> getTimeoutTest();
```
and generates the following code
```dart
@override
Future<Response<String>> getTimeoutTest() {
final Uri $url = Uri.parse('/test/get_timeout');
final Request $request = Request(
'GET',
$url,
client.baseUrl,
);
return client
.send<String, String>($request)
.timeout(const Duration(microseconds: 42000000));
}
```
---
Addresses #603
Addresses https://github.com/dart-lang/http/issues/1186
=> :sparkles: add per-request timeout

.github/workflows/dart.yml, chopper/CHANGELOG.md, chopper/lib/src/annotations.dart, chopper/pubspec.yaml, chopper/test/chain/interceptor_chain_test.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service.dart, chopper_built_value/CHANGELOG.md, chopper_built_value/pubspec.yaml, chopper_generator/CHANGELOG.md, chopper_generator/lib/src/generator.dart, chopper_generator/lib/src/utils.dart, chopper_generator/pubspec.yaml, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service.dart, mono_repo.yaml
:bookmark: pre-release v8.0.0-rc.2
- #604
- #604
- Require Chopper ^8.0.0
=> :bookmark: pre-release v8.0.0-rc.2

chopper/lib/src/interceptors/http_logging_interceptor.dart, chopper/test/http_logging_interceptor_test.dart
Add ability to `HttpLoggingInterceptor` to **only** log HTTP errors.
The `HttpLoggingInterceptor` amazing, however, due to its verbosity the level of output can sometimes seem overwhelming. Having the ability to only show verbose logs for HTTP errors is therefore in my mind a nice feature.
Passing `onlyErrors: true` to the constructor will limit the logger to only log **responses** with an HTTP status code of 400 and above.
---
This PR is a response/solution to @Guldem's https://github.com/lejard-h/chopper/pull/609#issuecomment-2098284779
=> :sparkles: add `onlyErrors` option to `HttpLoggingInterceptor`

chopper/CHANGELOG.md, chopper/lib/src/interceptors/http_logging_interceptor.dart, chopper/pubspec.yaml, chopper/test/http_logging_interceptor_test.dart, chopper_built_value/CHANGELOG.md, chopper_built_value/pubspec.yaml, chopper_generator/CHANGELOG.md, chopper_generator/pubspec.yaml, example/lib/built_value_resource.chopper.dart, example/lib/json_decode_service.activator.g.dart, example/lib/json_decode_service.vm.g.dart, example/lib/json_decode_service.worker.g.dart, example/lib/json_serializable.chopper.dart, example/pubspec.yaml
- #604
- **BREAKING CHANGE**:
- #547
- `RequestInterceptor` and Function `RequestInterceptor`s are removed 
- `ResponseInterceptor` and Function `ResponseInterceptor`s are removed
- See [Migrating to 8.0.0](https://docs.google.com/document/d/e/2PACX-1vQFoUDisnSJBzzXCMaf53ffUD1Bvpu-1GZ_stzfaaCa0Xd3WKIegbd1mmavEQcMT6r6v8z02UqloKuC/pub) for more information and examples
- #610
- #604
- **BREAKING CHANGE**:
- #547
- `RequestInterceptor` and Function `RequestInterceptor`s are removed 
- `ResponseInterceptor` and Function `ResponseInterceptor`s are removed
- See [Migrating to 8.0.0](https://docs.google.com/document/d/e/2PACX-1vQFoUDisnSJBzzXCMaf53ffUD1Bvpu-1GZ_stzfaaCa0Xd3WKIegbd1mmavEQcMT6r6v8z02UqloKuC/pub) for more information and examples
- Require Chopper ^8.0.0
=> :bookmark: release v8.0.0

SECURITY.md
I have preliminarily listed my email for the security reports. If someone else wants to take this over, please let me know.
=> :lock: add Security Policy

chopper/lib/src/interceptors/response_converter_interceptor.dart, chopper/test/chain/response_converter_interceptor_test.dart
=> 🐛 Fix null body converter

chopper/pubspec.yaml
In https://github.com/lejard-h/chopper/pull/627#issuecomment-2198520115 I forgot to bump the version in `chopper/pubspec.yaml` so there was no release to pub.dev.
CC / @JEuler @Guldem
=> :bookmark: release chopper v8.0.1+1 (for real)

chopper_generator/lib/src/generator.dart
While looking at the generator I found a duplicate null-coalescing `responseTypeReference`. Probably left there by mistake. It's not a bug per-se, it just looks up the response type 2x for no reason.
CC/ @Guldem
=> :art: remove duplicate null-coalescing responseTypeReference

chopper/lib/src/interceptors/curl_interceptor.dart, chopper/test/interceptors_test.dart
I noticed that a single quote `'` is not properly escaped in the cURL output so I escaped it according to [this](https://stackoverflow.com/questions/32122586).
For example
```dart
final fakeRequest = Request(
'POST',
Uri.parse('/'),
Uri.parse('base'),
body: r"""Lorem's ipsum "dolor" sit amet""",
);
```
should generate this cURL output
```
curl -v -X POST -H 'content-type: text/plain; charset=utf-8' -d 'Lorem'\''s ipsum "dolor" sit amet' 'base/'
```
and not fail when you paste it into your shell or Postman.
=> :bug: properly escape single quote in cURL interceptor output

chopper/example/definition.chopper.dart, chopper/example/tag.chopper.dart, chopper/lib/src/request.dart, chopper/pubspec.yaml, chopper/test/test_service.chopper.dart, chopper/test/test_service_base_url.chopper.dart, chopper/test/test_service_variable.chopper.dart, chopper/test/test_without_response_service.chopper.dart, chopper_generator/lib/src/generator.dart, chopper_generator/pubspec.yaml, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service_variable.chopper.dart, chopper_generator/test/test_without_response_service.chopper.dart
This pull request includes various updates and improvements to the `chopper` and `chopper_generator` packages, focusing on code formatting, dependency updates, and minor refactoring. Below are the most important changes:
* Added a comment to specify the dart format width in several generated files to ensure consistent code formatting. [[1]](diffhunk://#diff-21d059db28290c3d399331c65bb63c2e961f5f23845fbf7f1239eb97332b2541R1) [[2]](diffhunk://#diff-1baca8bda3c75d5938c379948a3f5507b629739efee872512889c8ada0816fceR1) [[3]](diffhunk://#diff-9208d1cd8bf5194350aa65706d974792f0d07ff11177b4144b7c70686912a307R1) [[4]](diffhunk://#diff-6b5f3751ae468c26ed71791628283df37af08c5aa6b26d357c2c97e69b7a31adR1) [[5]](diffhunk://#diff-8d6401771709f899198cf463c6b14d730520c9d9b0b5bb0988be4c48621ac92aR1) …
=> :arrow_up: update dependencies

.github/workflows/dart.yml, .github/workflows/publish.yml, .github/workflows/publish_dry_run.yml, chopper/CHANGELOG.md, chopper/example/definition.chopper.dart, chopper/example/tag.chopper.dart, chopper/lib/src/request.dart, chopper/pubspec.yaml, chopper/pubspec_overrides.yaml, chopper/test/test_service.chopper.dart, chopper/test/test_service_base_url.chopper.dart, chopper/test/test_service_variable.chopper.dart, chopper/test/test_without_response_service.chopper.dart, chopper_built_value/CHANGELOG.md, chopper_built_value/pubspec.yaml, chopper_built_value/pubspec_overrides.yaml, chopper_generator/CHANGELOG.md, chopper_generator/lib/src/generator.dart, chopper_generator/pubspec.yaml, chopper_generator/pubspec_overrides.yaml, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service_variable.chopper.dart, chopper_generator/test/test_without_response_service.chopper.dart
This pull request includes various updates to dependencies, improvements to workflow files, and minor code formatting changes across multiple files. The most important changes are summarized below:
* Updated `qs_dart` dependency to version 1.3.0 in `chopper/pubspec.yaml`.
* Updated `chopper_generator` dependency to version 8.0.3 in `chopper/pubspec.yaml`.
* Updated `chopper` dependency to version 8.0.3 in `chopper_built_value/pubspec.yaml`.
* Updated `analyzer` and `source_gen` dependencies in `chopper_generator/pubspec.yaml`.
* Updated `codecov-action` from version 4 to 5 in `.github/workflows/dart.yml` [[1]](diffhunk://#diff-c6fe895eea1e566d8f6f9f7e5f045b702d9bff8e60bfaec2d412193bd802ab2aL137-R137) [[2]](diffhunk://#diff-c6fe895eea1e566d8f6f9f7e5f045b702d9bff8e60bfaec2d412193bd802ab2aL15 …
=> :bookmark: release v8.0.4

chopper/lib/src/annotations.dart, chopper/test/test_service.dart, chopper/test/test_service_base_url.dart, chopper/test/test_service_variable.dart, chopper/test/test_without_response_service.dart, chopper_generator/lib/src/generator.dart, chopper_generator/test/test_service.dart, chopper_generator/test/test_service_variable.dart, chopper_generator/test/test_without_response_service.dart, example/lib/built_value_resource.dart, example/lib/json_serializable.dart
This pull request includes changes to the `chopper` library to standardize HTTP method annotations by replacing the old annotations with new uppercase versions and marking the old ones as deprecated. Additionally, it updates the test service to use the new annotations.
Standardization of HTTP method annotations:
* [`chopper/lib/src/annotations.dart`](diffhunk://#diff-39e351fa55b03968cafd0d33b766f30573fd6c9e469dfb16be24269696ea21c6R254-R278): Introduced new uppercase HTTP method annotations (`GET`, `POST`, `PUT`, `DELETE`, `PATCH`, `HEAD`, `OPTIONS`) and marked the old ones as deprecated. [[1]](diffhunk://#diff-39e351fa55b03968cafd0d33b766f30573fd6c9e469dfb16be24269696ea21c6R254-R278) [[2]](diffhunk://#diff-39e351fa55b03968cafd0d33b766f30573fd6c9e469dfb16be24269696ea21c6L269-R308) …
=> :alien: deprecate all lower-case method annotations

chopper/CHANGELOG.md, chopper/lib/src/annotations.dart, chopper/lib/src/converters.dart, chopper/lib/src/response.dart, chopper/pubspec.yaml, chopper/test/test_service.dart, chopper/test/test_service_base_url.dart, chopper/test/test_service_variable.dart, chopper/test/test_without_response_service.dart, chopper_generator/CHANGELOG.md, chopper_generator/lib/src/generator.dart, chopper_generator/pubspec.yaml, chopper_generator/test/test_service.dart, chopper_generator/test/test_service_variable.dart, chopper_generator/test/test_without_response_service.dart, example/lib/built_value_resource.dart, example/lib/json_serializable.dart
This pull request introduces several changes to the `chopper` package, primarily focusing on deprecating lower-case method annotations and updating the documentation to use upper-case annotations. Additionally, several new upper-case method annotations have been added, and the library version has been incremented. Below are the most important changes:
Deprecation and Introduction of Upper-Case Annotations:
* Deprecated all lower-case method annotations and introduced new upper-case annotations such as `GET`, `POST`, `PUT`, `DELETE`, `PATCH`, `HEAD`, and `OPTIONS` in `chopper/lib/src/annotations.dart`. [[1]](diffhunk://#diff-39e351fa55b03968cafd0d33b766f30573fd6c9e469dfb16be24269696ea21c6R254-R278) [[2]](diffhunk://#diff-39e351fa55b03968cafd0d33b766f30573fd6c9e469dfb16be24269696ea21c6L269-R …
=> :bookmark: release v8.1.0

faq.md, getting-started.md, requests.md
This pull request includes several changes to update HTTP method annotations in the documentation files to use uppercase versions. The changes ensure consistency and improve readability across the documentation.
* [`faq.md`](diffhunk://#diff-08c93eef774739f8dd6832484cc3801ccbb881da56ff2237df2ad1088048b1dbL70-R70): Updated HTTP method annotations from lowercase to uppercase in `compressRequest`, `ApiService`, and `TodosListService` classes. [[1]](diffhunk://#diff-08c93eef774739f8dd6832484cc3801ccbb881da56ff2237df2ad1088048b1dbL70-R70) [[2]](diffhunk://#diff-08c93eef774739f8dd6832484cc3801ccbb881da56ff2237df2ad1088048b1dbL134-R134) [[3]](diffhunk://#diff-08c93eef774739f8dd6832484cc3801ccbb881da56ff2237df2ad1088048b1dbL490-R490)
* [`getting-started.md`](diffhunk://#diff-f007f6cb65740b71d33ebd …
=> :memo: update HTTP verb capitalization in documentation

chopper/lib/src/annotations.dart, chopper/lib/src/converters.dart, chopper/test/annotations_test.chopper.dart, chopper/test/annotations_test.dart, chopper/test/authenticator_test.dart, chopper/test/base_test.dart, chopper/test/chopper_client_extended_test.dart, chopper/test/chopper_exception_test.dart, chopper/test/converter_test.dart, chopper/test/curl_interceptor_test.dart, chopper/test/helpers/fake_chain.dart, chopper/test/http_call_interceptor_test.dart, chopper/test/http_logging_interceptor_test.dart, chopper/test/request_stream_interceptor_test.dart, chopper/test/response_test.dart, chopper_built_value/test/converter_test.dart
This pull request introduces several updates to the `chopper` package, including improvements to method annotations, expanded test coverage, and the addition of new test cases. The most notable changes involve adding coverage ignores for specific constructors, enhancing testing for annotations, and introducing a new minimal authenticator for testing purposes.
* Added `// coverage:ignore-start` and `// coverage:ignore-end` markers to the constructors of HTTP method annotations (`GET`, `POST`, `DELETE`, `PUT`, `PATCH`, `HEAD`, `OPTIONS`) to exclude them from code coverage analysis. (`chopper/lib/src/annotations.dart`: [[1]](diffhunk://#diff-39e351fa55b03968cafd0d33b766f30573fd6c9e469dfb16be24269696ea21c6L269-R272) [[2]](diffhunk://#diff-39e351fa55b03968cafd0d33b766f30573fd6c9e469dfb16be24269 …
=> :white_check_mark: increase test coverage

chopper/CHANGELOG.md, chopper/README.md, chopper/pubspec.yaml, chopper_built_value/CHANGELOG.md, chopper_built_value/pubspec.yaml, chopper_generator/CHANGELOG.md, chopper_generator/lib/src/generator.dart, chopper_generator/lib/src/utils.dart, chopper_generator/pubspec.yaml
This pull request introduces updates to the Chopper library and its related packages to support the new Element2 API from the Dart analyzer. It also includes dependency updates and version bumps across the `chopper`, `chopper_built_value`, and `chopper_generator` packages. Below are the most significant changes grouped by their themes:
* Updated the `ChopperGenerator` implementation in `chopper_generator/lib/src/generator.dart` to replace `Element`, `ClassElement`, and related types with their corresponding `Element2` and `ClassElement2` counterparts. This includes changes to methods, parameters, and type checks to align with the Element2 API. [[1]](diffhunk://#diff-4ecb249f56dad1d5911519c4e273c8baec4af12f830ff29d138fa1f4c953167fL6-R6) …
=> :bookmark: release v8.3.0

chopper/example/definition.chopper.dart, chopper/example/tag.chopper.dart, chopper/test/annotations_test.chopper.dart, chopper/test/test_service.chopper.dart, chopper/test/test_service_base_url.chopper.dart, chopper/test/test_service_variable.chopper.dart, chopper/test/test_without_response_service.chopper.dart, chopper_generator/lib/src/generator.dart, chopper_generator/lib/src/utils.dart, chopper_generator/pubspec.yaml, chopper_generator/test/test_service.chopper.dart, chopper_generator/test/test_service_variable.chopper.dart, chopper_generator/test/test_without_response_service.chopper.dart
This pull request improves type checking robustness and accuracy in the `chopper_generator` codebase by updating how `TypeChecker` is constructed and used throughout the generator logic. It also makes minor dependency version adjustments and updates generated file headers for consistency.
**Type checking improvements:**
* Updated the `_typeChecker` helper in `generator.dart` to use `TypeChecker.typeNamed` with explicit `inPackage` or `inSdk` parameters, improving accuracy when resolving types from external packages or the Dart SDK. This change is reflected in all usages of `_typeChecker`, including checks for `ChopperService`, `Body`, `FieldMap`, `FactoryConverter`, `Map`, `String`, and `Response` types. [[1]](diffhunk://#diff-4ecb249f56dad1d5911519c4e273c8baec4af12f830ff29d138fa1f4c953167 …
=> :arrow_up: broaden version constraints for `build` and `source_gen` dependencies
