lejard-h/chopper

chopper/example/definition.chopper.dart
chopper/example/main.dart
chopper/lib/src/base.dart
chopper/pubspec.yaml
chopper/test/base_test.dart
chopper/test/form_test.dart
chopper/test/interceptors_test.dart
chopper/test/json_test.dart
chopper/test/test_service.chopper.dart
chopper_generator/pubspec.yaml
example/bin/main_built_value.dart
example/bin/main_jaguar_serializer.dart
example/bin/main_json_serializable.dart

Fix getting service by type

---

chopper_generator/lib/src/generator.dart

https://github.com/lejard-h/chopper/issues/41

Fixed @Path issue

---

chopper_generator/lib/src/generator.dart
chopper_generator/pubspec.yaml

for case user want to use custom url depend on path

avoid auto append '/' if baseUrl is empty 

---

chopper/lib/src/base.dart

Should assert that requests and responses are returned from interceptors

---

chopper/lib/src/annotations.dart

Adds a few small improvements to the documentation of annotations.
I could do the same with the rest of the project if needed.

Format and edit documentation in annotations.dart

---

faq.md

"Addressing" https://github.com/lejard-h/chopper/issues/122

HTTP Auth example

---

converters/converters.md
faq.md

Mostly Documentations change
No need to deploy on pub

Merge develop in master

---

chopper_generator/lib/src/generator.dart

I found myself browsing though the implementation of the generator to study how it works (great job @lejard-h btw!) and I made some code quality improvements along the way. I _really_ hope that I didn't break anything. Following up on this thought, I will look into writing tests for the generator. :]

Make code quality improvements in generator.dart

---

chopper/lib/src/request.dart

Preserve uri current query params in buildUri

---

chopper/lib/src/annotations.dart

Make conversion helpers can be `async`

---

.travis.yml
tool/publish.sh

Run publish script on master branch

Publish package from travis

---

chopper/README.md
chopper/lib/src/base.dart
chopper/lib/src/interceptor.dart
chopper/pubspec.yaml
chopper_built_value/README.md
chopper_built_value/lib/chopper_built_value.dart
chopper_built_value/pubspec.yaml
chopper_generator/README.md
chopper_generator/pubspec.yaml
converters/built-value-converter.md
converters/converters.md
example/pubspec.yaml

Another milestone on the road to the full docs update.
Still only inline public API doc and guide updates.

The Big Public API Documentation update, volume 2.

---

README.md
chopper/README.md
chopper/lib/src/annotations.dart
chopper_built_value/README.md
chopper_generator/README.md
getting-started.md
requests.md

Here's part 3 of the docs update.
This part has some new behavioral clarification too besides rewording the existing docs (addressing #195 mainly at the time of opening this PR).
Reviews are highly appreciated as always. 😄

The Big Public API Documentation Update, volume 3.

---

README.md

I would like to congratulate all people who work in that library and happy to add Flutter Favorite badge.

Add Flutter Favorite badge

---

README.md
chopper/README.md

Make the badge fit more nicely in the README

Fix Flutter favorites badge

---

chopper_built_value/lib/chopper_built_value.dart
chopper_built_value/pubspec.yaml
chopper_built_value/test/converter_test.dart
chopper_built_value/test/data.g.dart

Manual migration to null safety

chopper_built_value - null safety support

---

converters/converters.md

I've found and fixed a small typo in converters.md.

Fix typo in converters.md

---

.github/workflows/dart.yml
chopper_built_value/mono_pkg.yaml

add test to mono_pkg.yaml and regenerate dart.yaml

Add chopper_built_value to github actions

---

chopper/lib/src/base.dart
chopper/lib/src/request.dart

Make all Map and List non nullable

Cleanup nullable Map/List APIs

---

chopper/CHANGELOG.md
chopper/pubspec.yaml
chopper_built_value/CHANGELOG.md
chopper_built_value/pubspec.yaml
chopper_generator/CHANGELOG.md
chopper_generator/pubspec.yaml

Great job all !
- @fryette 
- @Vovanella95 
- @JEuler
- @stewemetal

Null safety stable

---

chopper/lib/src/base.dart
chopper_generator/lib/chopper_generator.dart
chopper_generator/lib/src/generator.dart

Fix Header Option Casting

---

chopper/lib/src/base.dart

Credits to @imatok. (https://github.com/lejard-h/chopper/issues/259). Tests are passing and the code seems valid.

Fix for #259

---

chopper_generator/lib/src/generator.dart

Reverting the stuff for https://github.com/lejard-h/chopper/issues/258

Interpolation fixes

---

chopper/lib/src/annotations.dart
chopper_generator/lib/src/generator.dart

I try to add @FiledMap @PartMap @PartFileMap to chopper library.
Also add generator codes and test them.

Add @FiledMap @PartMap @PartFileMap

---

.github/workflows/dart.yml
tool/ci.sh

This fixes https://github.com/google/mono_repo.dart/issues/421 and https://github.com/lejard-h/chopper/pull/375#issuecomment-1279684386

Update mono_repo to 6.4.2

---

.github/ISSUE_TEMPLATE/feature_request.md

This is a continuation of https://github.com/lejard-h/chopper/pull/359
As the Github issues keep mounting, it would be wise to keep them organised. So I've decided to add another Github issue template - this time for a Feature request / Enhancement.

Add Feature request Github issue template

---

.github/workflows/publish.yml

The 3rd attempt of https://github.com/lejard-h/chopper/pull/418
* [FIX] https://github.com/lejard-h/chopper/pull/419
* [FIX] https://github.com/lejard-h/chopper/pull/421
* [CHORE] https://github.com/lejard-h/chopper/pull/417

:bookmark: release v6.1.2 (3rd attempt)

---

.github/workflows/publish.yml

Fixes a critical typo made in https://github.com/lejard-h/chopper/pull/424

:bug: fix publish CI to run only on push

---

chopper/CHANGELOG.md
chopper/lib/src/request.dart
chopper/pubspec.yaml
chopper/test/multipart_test.dart
chopper/test/test_service.chopper.dart
chopper/test/test_service.dart

- [FIX] Fix Multipart for List<int> and List<String> ([#439](https://github.com/lejard-h/chopper/pull/439))

:bookmark: release v6.1.4

---

chopper/lib/src/base.dart
chopper/lib/src/interceptor.dart
chopper/lib/src/utils.dart
chopper/test/base_test.dart

:recycle: refactor chopper

---

.github/dependabot.yml

Add [Dependabot security updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/about-dependabot-security-updates)

:construction_worker: Dependabot security updates

---

chopper/CHANGELOG.md
chopper/lib/src/chopper_log_record.dart
chopper/lib/src/http_logging_interceptor.dart
chopper/pubspec.yaml

:bookmark: release v7.0.3

---

chopper/CHANGELOG.md
chopper/lib/chopper.dart
chopper/lib/src/chopper_log_record.dart
chopper/pubspec.yaml

:bookmark: release v7.0.4

---

chopper/CHANGELOG.md
chopper/README.md
chopper/pubspec.yaml

:bookmark: release chopper v7.0.5

---

chopper/pubspec.yaml
chopper_built_value/pubspec.yaml
chopper_generator/pubspec.yaml

Add [pub.dev topics](https://pub.dev/topics)

:label: add pub.dev topics to package metadata

---

chopper/CHANGELOG.md
chopper/lib/src/annotations.dart
chopper/lib/src/base.dart
chopper/lib/src/interceptor.dart
chopper/pubspec.yaml
chopper/test/base_test.dart
chopper/test/converter_test.dart
chopper/test/ensure_build_test.dart
chopper/test/test_service_variable.chopper.dart
chopper/test/test_service_variable.dart
chopper_built_value/CHANGELOG.md
chopper_built_value/pubspec.yaml
chopper_generator/CHANGELOG.md
chopper_generator/lib/src/generator.dart
chopper_generator/pubspec.yaml
chopper_generator/test/ensure_build_test.dart
chopper_generator/test/test_service_variable.chopper.dart
chopper_generator/test/test_service_variable.dart

- #493
- #497
- #495
- #495
- #493
- #495

:bookmark: release v7.0.6

---

chopper/example/definition.chopper.dart
chopper/test/test_service.chopper.dart
chopper/test/test_service_variable.chopper.dart
chopper_generator/CHANGELOG.md
chopper_generator/lib/src/generator.dart
chopper_generator/pubspec.yaml
chopper_generator/test/test_service.chopper.dart
chopper_generator/test/test_service_variable.chopper.dart

:bookmark: release chopper generator v7.0.4

---

chopper/analysis_options.yaml
chopper/example/definition.chopper.dart
chopper/test/test_service.chopper.dart
chopper/test/test_service_variable.chopper.dart
chopper_built_value/analysis_options.yaml
chopper_generator/Makefile
chopper_generator/analysis_options.yaml
chopper_generator/lib/src/generator.dart
chopper_generator/test/test_service.chopper.dart
chopper_generator/test/test_service_variable.chopper.dart
example/analysis_options.yaml
example/lib/built_value_resource.chopper.dart
example/lib/json_serializable.chopper.dart

:rotating_light: correct static analysis suppression of *.chopper.dart files

---

chopper/lib/src/request.dart
chopper/test/base_test.dart

:bug: remove charset from http request headers when the body is in bytes

---

.github/workflows/dart.yml
tool/ci.sh

Update [mono_repo](https://pub.dev/packages/mono_repo)

:construction_worker: update mono_repo

---

.github/workflows/dart.yml
.github/workflows/publish.yml
.github/workflows/publish_dry_run.yml
chopper/CHANGELOG.md
chopper/analysis_options.yaml
chopper/example/definition.chopper.dart
chopper/lib/src/request.dart
chopper/pubspec.yaml
chopper/test/base_test.dart
chopper/test/test_service.chopper.dart
chopper/test/test_service_variable.chopper.dart
chopper_built_value/analysis_options.yaml
chopper_generator/CHANGELOG.md
chopper_generator/Makefile
chopper_generator/analysis_options.yaml
chopper_generator/lib/src/generator.dart
chopper_generator/pubspec.yaml
chopper_generator/test/test_service.chopper.dart
chopper_generator/test/test_service_variable.chopper.dart
example/analysis_options.yaml
example/lib/built_value_resource.chopper.dart
example/lib/json_serializable.chopper.dart
tool/ci.sh

:bookmark: release chopper v7.0.7 and chopper_generator v7.0.5

---

.github/workflows/publish.yml

Forgot to add [the required permissions](https://github.com/softprops/action-gh-release#permissions)
```yaml
permissions:
contents: write
```
🙈

:green_heart: fix publish workflow permissions

---

chopper/CHANGELOG.md
chopper/pubspec.yaml
chopper_built_value/CHANGELOG.md
chopper_built_value/pubspec.yaml
chopper_generator/CHANGELOG.md
chopper_generator/pubspec.yaml

:bookmark: release v7.0.7+1

---

chopper/CHANGELOG.md
chopper/lib/src/utils.dart
chopper/pubspec.yaml
chopper/test/base_test.dart
chopper/test/test_service.chopper.dart
chopper/test/test_service.dart

:bookmark: release chopper v7.0.8

---

chopper/test/base_test.dart
chopper/test/ensure_build_test.dart
chopper/test/test_service_base_url.chopper.dart
chopper/test/test_service_base_url.dart
chopper_generator/CHANGELOG.md
chopper_generator/lib/src/generator.dart
chopper_generator/pubspec.yaml

:bookmark: release chopper_generator v7.0.6

---

.github/dependabot.yml

Ensures that all Github Actions are always up-to-date
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

:construction_worker: use Dependabot to check for workflow action updates

---

.github/dependabot.yml
chopper_generator/CHANGELOG.md
chopper_generator/lib/src/builder_factory.dart
chopper_generator/pubspec.yaml

:bookmark: release chopper_generator v7.1.1

---

chopper/CHANGELOG.md
chopper/lib/src/annotations.dart
chopper/pubspec.yaml
faq.md

:bookmark: release chopper v7.1.1

---

chopper/test/chain/interceptor_chain_test.dart

Added test to verify these are passed up in the chain.
See https://github.com/lejard-h/chopper/issues/167
Was bit to quick with cleaning up the branches on my github 🤦 
See #600 for the first PR...

:white_check_mark: Added test to see if exception are passed up

---

.github/workflows/dart.yml
mono_repo.yaml

:green_heart: fix Codecov CI

---

chopper/CHANGELOG.md
chopper/lib/src/interceptors/curl_interceptor.dart
chopper/pubspec.yaml
chopper/test/interceptors_test.dart
chopper_generator/CHANGELOG.md
chopper_generator/lib/src/generator.dart
chopper_generator/pubspec.yaml

:bookmark: release v8.0.2

---

chopper/CHANGELOG.md
chopper/lib/chopper.dart
chopper/pubspec.yaml
chopper_built_value/CHANGELOG.md
chopper_built_value/pubspec.yaml
chopper_built_value/test/serializers.dart
chopper_generator/CHANGELOG.md
chopper_generator/lib/chopper_generator.dart
chopper_generator/pubspec.yaml

:bookmark: release v8.0.3
- Remove unnecessary library name
- Remove unnecessary library name
- Remove unnecessary library name

:bookmark: release v8.0.3

---

chopper/CHANGELOG.md
chopper/pubspec.yaml
chopper_built_value/CHANGELOG.md
chopper_built_value/pubspec.yaml
chopper_generator/CHANGELOG.md
chopper_generator/pubspec.yaml

I need to sync the master and dev branches before releasing v8.0.4.
I forgot to do that after releasing v8.0.3 back in October. 😅

:twisted_rightwards_arrows: post rease branch sync

---

chopper/CHANGELOG.md
chopper/pubspec.yaml
chopper_generator/CHANGELOG.md
chopper_generator/pubspec.yaml

This pull request introduces version 8.2.0 for both the `chopper` and `chopper_generator` packages, adding a new feature to enhance date serialization while updating dependencies and versioning.
* Added `DateFormat` to enhance date serialization options, documented in the changelogs for both `chopper` and `chopper_generator`. [[1]](diffhunk://#diff-bf1702a19bd5925e6c580bc5dd7448547c90d381a25d9f493ead242c9f2cd4a7R3-R6) [[2]](diffhunk://#diff-a72b8ecaf626b51da52558459c559dea51037af8ba72e7da9447d674ba1b15e8R3-R6)
* Updated the version of `chopper` to 8.2.0 in `chopper/pubspec.yaml`.
* Updated the version of `chopper_generator` to 8.2.0 in `chopper_generator/pubspec.yaml`.
* Updated `chopper_generator` dependency in `chopper/pubspec.yaml` to version ^8.1.0.
* Updated `chopper` dependency in …

:twisted_rightwards_arrows: post release branch sync

---

chopper/pubspec.yaml
chopper_built_value/pubspec.yaml
chopper_generator/lib/src/generator.dart
chopper_generator/lib/src/utils.dart
chopper_generator/pubspec.yaml

This pull request updates dependencies and introduces significant changes to the `ChopperGenerator` codebase to support the latest version of the Dart Analyzer. The key updates include dependency upgrades across multiple packages and refactoring the `ChopperGenerator` class to align with the new Dart Analyzer API.
* Updated dependencies in `chopper/pubspec.yaml`, `chopper_built_value/pubspec.yaml`, and `chopper_generator/pubspec.yaml` to newer versions, including `analyzer`, `http`, `build_runner`, and others. These updates ensure compatibility with Dart SDK 3.0 and enhance stability. [[1]](diffhunk://#diff-c7bda5cb4208050349dcb19de97acd43bb7dfbc5eda9b87acc22e3193c1bc158L3-R29) [[2]](diffhunk://#diff-0ffd7bfcac81d718b89496926d70952c8bbad1d6327fc46b5aebacb68dbb1197L3-R21) …

:arrow_up: update analyzer and dependencies to use element2 API
